import Head from 'next/head'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'

export default function AboutMe() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Practice App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <p>this page is working</p>
    </div>
  )
}